# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

platform :ios, '10.0'
inhibit_all_warnings!

target 'AquaSports' do 
# Comment the next line if you don't want to use dynamic frameworks 
  use_frameworks! 
# Pods for AquaSports 
  pod 'Firebase/Analytics'
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Storage'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'
  pod 'FirebaseFirestoreSwift'
  pod 'GoogleMaps'
  pod 'GooglePlaces' 
end
